// This file is auto-generated by scripts/extract-openapi-constants.mjs
// Do not edit. Source: openapi.json → x-ox1audio-constants
// Types: use ~/client types.gen (hey-api) or typeof on these consts.

export const OX1AUDIO_CONSTANTS = {
  "playlistColors": [
    {
      "value": "light_blue",
      "label": "Light blue",
      "hint": "air, sky, soft focus",
      "hexes": [
        "#8ec5e8",
        "#5ea3d4",
        "#3a7aad"
      ]
    },
    {
      "value": "washed_blue",
      "label": "Washed blue",
      "hint": "melancholy, rainy, wistful",
      "hexes": [
        "#9bb0c2",
        "#6f879c",
        "#4a5f70"
      ]
    },
    {
      "value": "dark_blue",
      "label": "Dark blue",
      "hint": "night, deep focus, cool",
      "hexes": [
        "#3d6f9e",
        "#2a4f78",
        "#1a334f"
      ]
    },
    {
      "value": "teal",
      "label": "Teal",
      "hint": "calm, aquatic, clean",
      "hexes": [
        "#5db8b0",
        "#3a8f8a",
        "#256660"
      ]
    },
    {
      "value": "mint",
      "label": "Mint",
      "hint": "fresh, light, breezy",
      "hexes": [
        "#8fd4b8",
        "#5fb893",
        "#3d8568"
      ]
    },
    {
      "value": "green",
      "label": "Green",
      "hint": "nature, growth, easy",
      "hexes": [
        "#7cbc6e",
        "#549a4a",
        "#3a6e35"
      ]
    },
    {
      "value": "forest",
      "label": "Forest",
      "hint": "earthy, grounded, dense",
      "hexes": [
        "#4f8a5b",
        "#356344",
        "#234331"
      ]
    },
    {
      "value": "yellow",
      "label": "Yellow",
      "hint": "bright, sunny, playful",
      "hexes": [
        "#e8d06a",
        "#d4b23a",
        "#a88820"
      ]
    },
    {
      "value": "amber",
      "label": "Amber",
      "hint": "warm, golden hour",
      "hexes": [
        "#e8b45a",
        "#d4922e",
        "#a86c1c"
      ]
    },
    {
      "value": "orange",
      "label": "Orange",
      "hint": "energetic, upbeat",
      "hexes": [
        "#e8924a",
        "#d06e28",
        "#a0501c"
      ]
    },
    {
      "value": "coral",
      "label": "Coral",
      "hint": "friendly, lively",
      "hexes": [
        "#e88878",
        "#d05e50",
        "#a04038"
      ]
    },
    {
      "value": "light_red",
      "label": "Light red",
      "hint": "warm affection",
      "hexes": [
        "#e89890",
        "#d46a62",
        "#b04842"
      ]
    },
    {
      "value": "rose",
      "label": "Rose",
      "hint": "romantic, tender",
      "hexes": [
        "#d87890",
        "#b85068",
        "#8a3850"
      ]
    },
    {
      "value": "dark_red",
      "label": "Dark red",
      "hint": "intense, passionate",
      "hexes": [
        "#b84848",
        "#8a3030",
        "#5c2020"
      ]
    },
    {
      "value": "pink",
      "label": "Pink",
      "hint": "sweet, dreamy",
      "hexes": [
        "#e8a0c0",
        "#d070a0",
        "#a84878"
      ]
    },
    {
      "value": "magenta",
      "label": "Magenta",
      "hint": "bold, nightlife",
      "hexes": [
        "#d060b0",
        "#a83888",
        "#782060"
      ]
    },
    {
      "value": "lavender",
      "label": "Lavender",
      "hint": "soft, dreamy ambient",
      "hexes": [
        "#b8a8d8",
        "#9080c0",
        "#685898"
      ]
    },
    {
      "value": "purple",
      "label": "Purple",
      "hint": "creative, lush",
      "hexes": [
        "#9a68c8",
        "#7848a8",
        "#543078"
      ]
    },
    {
      "value": "violet",
      "label": "Violet",
      "hint": "mysterious, lush night",
      "hexes": [
        "#8858c0",
        "#6838a0",
        "#482870"
      ]
    },
    {
      "value": "indigo",
      "label": "Indigo",
      "hint": "deep, contemplative",
      "hexes": [
        "#6878c8",
        "#4858a8",
        "#303878"
      ]
    },
    {
      "value": "slate",
      "label": "Slate",
      "hint": "neutral, grey, balanced",
      "hexes": [
        "#8a96a8",
        "#5e6a7c",
        "#3e4858"
      ]
    },
    {
      "value": "charcoal",
      "label": "Charcoal",
      "hint": "dark, moody, minimal",
      "hexes": [
        "#5a6068",
        "#3a4048",
        "#242830"
      ]
    }
  ],
  "password": {
    "minLength": 8,
    "maxLength": 128,
    "rules": [
      {
        "id": "length",
        "label": "At least 8 characters",
        "kind": "min_length"
      },
      {
        "id": "upper",
        "label": "One uppercase letter",
        "kind": "has_upper"
      },
      {
        "id": "lower",
        "label": "One lowercase letter",
        "kind": "has_lower"
      },
      {
        "id": "number",
        "label": "One number",
        "kind": "has_digit"
      },
      {
        "id": "special",
        "label": "One special character",
        "kind": "has_special"
      }
    ]
  },
  "allowedAudioExtensions": [
    ".mp3",
    ".wav",
    ".flac",
    ".m4a",
    ".ogg",
    ".aac"
  ],
  "allowedImageMimeTypes": [
    "image/jpeg",
    "image/png",
    "image/webp"
  ],
  "fallbackCoverColor": "#64748b",
  "coverColorRanking": {
    "chromaBias": 0.35,
    "defaultLimit": 4
  }
} as const

export const PLAYLIST_COLORS = OX1AUDIO_CONSTANTS.playlistColors
export const PASSWORD = OX1AUDIO_CONSTANTS.password
export const ALLOWED_AUDIO_EXTENSIONS = OX1AUDIO_CONSTANTS.allowedAudioExtensions
export const ALLOWED_IMAGE_MIME_TYPES = OX1AUDIO_CONSTANTS.allowedImageMimeTypes
export const FALLBACK_COVER_COLOR = OX1AUDIO_CONSTANTS.fallbackCoverColor
export const COVER_COLOR_RANKING = OX1AUDIO_CONSTANTS.coverColorRanking
