// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * AppendMessageBody
 */
export type AppendMessageBody = {
    /**
     * Message
     */
    message: string;
};

/**
 * AppendMessageOut
 */
export type AppendMessageOut = {
    /**
     * Messages
     */
    messages: Array<ChatMessageOut>;
    /**
     * Tracks
     */
    tracks: Array<TrackOut>;
    /**
     * Playlists
     */
    playlists?: Array<PlaylistChatOut>;
};

/**
 * ArtistListOut
 */
export type ArtistListOut = {
    /**
     * Items
     */
    items: Array<ArtistOut>;
    /**
     * Total
     */
    total: number;
    /**
     * Limit
     */
    limit: number;
    /**
     * Offset
     */
    offset: number;
};

/**
 * ArtistOut
 */
export type ArtistOut = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Track Count
     */
    track_count?: number;
    /**
     * Has Image
     */
    has_image?: boolean;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * ArtistRefOut
 */
export type ArtistRefOut = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
};

/**
 * AuthCredentials
 */
export type AuthCredentials = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
};

/**
 * AuthStatus
 */
export type AuthStatus = {
    /**
     * Registration Open
     */
    registration_open: boolean;
};

/**
 * Body_searchAudio
 */
export type BodySearchAudio = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * Body_updateMyAvatar
 */
export type BodyUpdateMyAvatar = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * Body_updateTrackCover
 */
export type BodyUpdateTrackCover = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * Body_uploadTrack
 */
export type BodyUploadTrack = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * Body_uploadZip
 */
export type BodyUploadZip = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * ChangeEmailBody
 */
export type ChangeEmailBody = {
    /**
     * Current Password
     */
    current_password: string;
    /**
     * New Email
     */
    new_email: string;
};

/**
 * ChangePasswordBody
 */
export type ChangePasswordBody = {
    /**
     * Current Password
     */
    current_password?: string | null;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * ChatDetailOut
 */
export type ChatDetailOut = {
    /**
     * Id
     */
    id: string;
    /**
     * Title
     */
    title: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Messages
     */
    messages: Array<ChatMessageOut>;
    /**
     * Tracks
     */
    tracks?: Array<TrackOut>;
    /**
     * Playlists
     */
    playlists?: Array<PlaylistChatOut>;
};

/**
 * ChatMessageOut
 */
export type ChatMessageOut = {
    /**
     * Id
     */
    id: string;
    /**
     * Role
     */
    role: 'user' | 'assistant';
    /**
     * Content
     */
    content: string;
    /**
     * Tool Traces
     */
    tool_traces?: Array<ToolTraceOut> | null;
    /**
     * Track Ids
     */
    track_ids?: Array<string> | null;
    /**
     * Playlist Ids
     */
    playlist_ids?: Array<string> | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * ChatSummaryOut
 */
export type ChatSummaryOut = {
    /**
     * Id
     */
    id: string;
    /**
     * Title
     */
    title: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * CreateArtistBody
 */
export type CreateArtistBody = {
    /**
     * Name
     */
    name: string;
};

/**
 * CreateChatBody
 */
export type CreateChatBody = {
    /**
     * Message
     */
    message: string;
};

/**
 * CreatePlaylistBody
 */
export type CreatePlaylistBody = {
    /**
     * Title
     */
    title: string;
    color: PlaylistColor;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Track Ids
     */
    track_ids?: Array<string> | null;
};

/**
 * DeleteTracksBody
 */
export type DeleteTracksBody = {
    /**
     * Track Ids
     */
    track_ids: Array<string>;
};

/**
 * GraphLinkOut
 */
export type GraphLinkOut = {
    /**
     * Source
     */
    source: string;
    /**
     * Target
     */
    target: string;
    /**
     * Weight
     */
    weight: number;
    /**
     * Audio Weight
     */
    audio_weight: number;
    /**
     * Profile Weight
     */
    profile_weight: number;
    /**
     * Reasons
     */
    reasons: Array<string>;
};

/**
 * GraphNodeOut
 */
export type GraphNodeOut = {
    track: TrackOut;
};

/**
 * GraphResponseOut
 */
export type GraphResponseOut = {
    /**
     * Nodes
     */
    nodes: Array<GraphNodeOut>;
    /**
     * Links
     */
    links: Array<GraphLinkOut>;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * ImportJobOut
 */
export type ImportJobOut = {
    /**
     * Id
     */
    id: string;
    /**
     * Original Filename
     */
    original_filename: string;
    status: JobStatus;
    /**
     * Total Files
     */
    total_files: number;
    /**
     * Processed Files
     */
    processed_files: number;
    /**
     * Failed Files
     */
    failed_files: number;
    /**
     * Error Message
     */
    error_message: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * JobOut
 *
 * Catalog job with indexing progress (ZIP import → ML index).
 */
export type JobOut = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Phase
     */
    phase: 'queued' | 'importing' | 'indexing' | 'complete' | 'failed';
    /**
     * Total Files
     */
    total_files: number;
    /**
     * Ready Files
     */
    ready_files: number;
    /**
     * Pending Files
     */
    pending_files: number;
    /**
     * Failed Files
     */
    failed_files: number;
    /**
     * Error Message
     */
    error_message: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * JobStatus
 */
export type JobStatus = 'queued' | 'running' | 'complete' | 'failed';

/**
 * PlaylistChatOut
 */
export type PlaylistChatOut = {
    /**
     * Id
     */
    id: string;
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description: string | null;
    /**
     * Color
     */
    color?: string | null;
    /**
     * Theme Colors
     */
    theme_colors?: Array<string>;
    /**
     * Track Count
     */
    track_count: number;
    /**
     * Preview Tracks
     */
    preview_tracks?: Array<TrackOut>;
};

/**
 * PlaylistColor
 */
export type PlaylistColor = 'light_blue' | 'washed_blue' | 'dark_blue' | 'teal' | 'mint' | 'green' | 'forest' | 'yellow' | 'amber' | 'orange' | 'coral' | 'light_red' | 'rose' | 'dark_red' | 'pink' | 'magenta' | 'lavender' | 'purple' | 'violet' | 'indigo' | 'slate' | 'charcoal';

/**
 * PlaylistDetailOut
 */
export type PlaylistDetailOut = {
    /**
     * Id
     */
    id: string;
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description: string | null;
    color?: PlaylistColor | null;
    /**
     * Theme Colors
     */
    theme_colors?: Array<string>;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Tracks
     */
    tracks: Array<TrackOut>;
};

/**
 * PlaylistSummaryOut
 */
export type PlaylistSummaryOut = {
    /**
     * Id
     */
    id: string;
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description: string | null;
    color?: PlaylistColor | null;
    /**
     * Theme Colors
     */
    theme_colors?: Array<string>;
    /**
     * Track Count
     */
    track_count: number;
    /**
     * Cover Colors
     */
    cover_colors?: Array<string>;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * PlaylistTracksBody
 */
export type PlaylistTracksBody = {
    /**
     * Track Ids
     */
    track_ids: Array<string>;
    /**
     * Position
     */
    position?: number | null;
};

/**
 * RegisterBody
 */
export type RegisterBody = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Display Name
     */
    display_name?: string | null;
};

/**
 * RemovePlaylistTracksBody
 */
export type RemovePlaylistTracksBody = {
    /**
     * Track Ids
     */
    track_ids: Array<string>;
};

/**
 * ReorderPlaylistBody
 */
export type ReorderPlaylistBody = {
    /**
     * Track Ids
     */
    track_ids: Array<string>;
};

/**
 * SearchHitOut
 */
export type SearchHitOut = {
    track: TrackOut;
    /**
     * Score
     */
    score: number;
    /**
     * Track Score
     */
    track_score: number;
    /**
     * Best Segment Score
     */
    best_segment_score: number;
    /**
     * Segment Coverage
     */
    segment_coverage: number;
    /**
     * Match Scope
     */
    match_scope: string;
    /**
     * Matched Segment Ids
     */
    matched_segment_ids: Array<string>;
    /**
     * Reasons
     */
    reasons: Array<string>;
};

/**
 * SearchMode
 */
export type SearchMode = 'tracks' | 'segments';

/**
 * SearchResponseOut
 */
export type SearchResponseOut = {
    /**
     * Results
     */
    results: Array<SearchHitOut>;
};

/**
 * SearchTextBody
 */
export type SearchTextBody = {
    /**
     * Query
     */
    query: string;
    /**
     * Negative Query
     */
    negative_query?: string | null;
    /**
     * Top K
     */
    top_k?: number;
    mode?: SearchMode;
};

/**
 * ToolTraceOut
 */
export type ToolTraceOut = {
    /**
     * Name
     */
    name: string;
    /**
     * Args
     */
    args: {
        [key: string]: unknown;
    };
    /**
     * Ok
     */
    ok: boolean;
};

/**
 * TrackListOut
 */
export type TrackListOut = {
    /**
     * Items
     */
    items: Array<TrackOut>;
    /**
     * Total
     */
    total: number;
    /**
     * Limit
     */
    limit: number;
    /**
     * Offset
     */
    offset: number;
};

/**
 * TrackOut
 */
export type TrackOut = {
    /**
     * Id
     */
    id: string;
    /**
     * Title
     */
    title: string;
    /**
     * Artist
     */
    artist: string;
    /**
     * Original Filename
     */
    original_filename: string;
    /**
     * Content Type
     */
    content_type: string;
    /**
     * Size Bytes
     */
    size_bytes: number;
    status: TrackStatus;
    /**
     * Error Message
     */
    error_message: string | null;
    /**
     * Imported At
     */
    imported_at: string;
    /**
     * Indexed At
     */
    indexed_at: string | null;
    /**
     * Cover Color
     */
    cover_color?: string | null;
    /**
     * Has Cover
     */
    has_cover?: boolean;
    /**
     * Duration S
     */
    duration_s?: number | null;
    /**
     * Is Instrumental
     */
    is_instrumental?: boolean | null;
    /**
     * Artists
     */
    artists?: Array<ArtistRefOut>;
};

/**
 * TrackStatus
 */
export type TrackStatus = 'uploading' | 'queued' | 'indexing' | 'ready' | 'failed';

/**
 * UpdatePlaylistBody
 */
export type UpdatePlaylistBody = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Clear Description
     */
    clear_description?: boolean;
    color?: PlaylistColor | null;
};

/**
 * UpdateProfileBody
 */
export type UpdateProfileBody = {
    /**
     * Display Name
     */
    display_name: string;
};

/**
 * UpdateTrackBody
 */
export type UpdateTrackBody = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * Artist Ids
     */
    artist_ids?: Array<string> | null;
};

/**
 * UserOut
 */
export type UserOut = {
    /**
     * Id
     */
    id: string;
    /**
     * Email
     */
    email: string;
    role: UserRole;
    /**
     * Display Name
     */
    display_name?: string | null;
    /**
     * Must Change Password
     */
    must_change_password?: boolean;
    /**
     * Has Avatar
     */
    has_avatar?: boolean;
};

/**
 * UserRole
 */
export type UserRole = 'master' | 'user';

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * WaveformOut
 */
export type WaveformOut = {
    /**
     * Duration S
     */
    duration_s: number;
    /**
     * Samples
     */
    samples: Array<number>;
};

export type GetApiV1AuthStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/status';
};

export type GetApiV1AuthStatusResponses = {
    /**
     * Successful Response
     */
    200: AuthStatus;
};

export type GetApiV1AuthStatusResponse = GetApiV1AuthStatusResponses[keyof GetApiV1AuthStatusResponses];

export type PostApiV1AuthRegisterData = {
    body: RegisterBody;
    path?: never;
    query?: never;
    url: '/api/v1/auth/register';
};

export type PostApiV1AuthRegisterErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostApiV1AuthRegisterError = PostApiV1AuthRegisterErrors[keyof PostApiV1AuthRegisterErrors];

export type PostApiV1AuthRegisterResponses = {
    /**
     * Successful Response
     */
    201: UserOut;
};

export type PostApiV1AuthRegisterResponse = PostApiV1AuthRegisterResponses[keyof PostApiV1AuthRegisterResponses];

export type PostApiV1AuthUsersData = {
    body: AuthCredentials;
    path?: never;
    query?: never;
    url: '/api/v1/auth/users';
};

export type PostApiV1AuthUsersErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostApiV1AuthUsersError = PostApiV1AuthUsersErrors[keyof PostApiV1AuthUsersErrors];

export type PostApiV1AuthUsersResponses = {
    /**
     * Successful Response
     */
    201: UserOut;
};

export type PostApiV1AuthUsersResponse = PostApiV1AuthUsersResponses[keyof PostApiV1AuthUsersResponses];

export type PostApiV1AuthLoginData = {
    body: AuthCredentials;
    path?: never;
    query?: never;
    url: '/api/v1/auth/login';
};

export type PostApiV1AuthLoginErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostApiV1AuthLoginError = PostApiV1AuthLoginErrors[keyof PostApiV1AuthLoginErrors];

export type PostApiV1AuthLoginResponses = {
    /**
     * Successful Response
     */
    200: UserOut;
};

export type PostApiV1AuthLoginResponse = PostApiV1AuthLoginResponses[keyof PostApiV1AuthLoginResponses];

export type PostApiV1AuthLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/logout';
};

export type PostApiV1AuthLogoutResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type PostApiV1AuthLogoutResponse = PostApiV1AuthLogoutResponses[keyof PostApiV1AuthLogoutResponses];

export type GetApiV1AuthMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/me';
};

export type GetApiV1AuthMeResponses = {
    /**
     * Successful Response
     */
    200: UserOut;
};

export type GetApiV1AuthMeResponse = GetApiV1AuthMeResponses[keyof GetApiV1AuthMeResponses];

export type PatchApiV1AuthMeData = {
    body: UpdateProfileBody;
    path?: never;
    query?: never;
    url: '/api/v1/auth/me';
};

export type PatchApiV1AuthMeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PatchApiV1AuthMeError = PatchApiV1AuthMeErrors[keyof PatchApiV1AuthMeErrors];

export type PatchApiV1AuthMeResponses = {
    /**
     * Successful Response
     */
    200: UserOut;
};

export type PatchApiV1AuthMeResponse = PatchApiV1AuthMeResponses[keyof PatchApiV1AuthMeResponses];

export type PostApiV1AuthMePasswordData = {
    body: ChangePasswordBody;
    path?: never;
    query?: never;
    url: '/api/v1/auth/me/password';
};

export type PostApiV1AuthMePasswordErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostApiV1AuthMePasswordError = PostApiV1AuthMePasswordErrors[keyof PostApiV1AuthMePasswordErrors];

export type PostApiV1AuthMePasswordResponses = {
    /**
     * Successful Response
     */
    200: UserOut;
};

export type PostApiV1AuthMePasswordResponse = PostApiV1AuthMePasswordResponses[keyof PostApiV1AuthMePasswordResponses];

export type PostApiV1AuthMeEmailData = {
    body: ChangeEmailBody;
    path?: never;
    query?: never;
    url: '/api/v1/auth/me/email';
};

export type PostApiV1AuthMeEmailErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostApiV1AuthMeEmailError = PostApiV1AuthMeEmailErrors[keyof PostApiV1AuthMeEmailErrors];

export type PostApiV1AuthMeEmailResponses = {
    /**
     * Successful Response
     */
    200: UserOut;
};

export type PostApiV1AuthMeEmailResponse = PostApiV1AuthMeEmailResponses[keyof PostApiV1AuthMeEmailResponses];

export type GetApiV1AuthMeAvatarData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/me/avatar';
};

export type GetApiV1AuthMeAvatarResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type PutApiV1AuthMeAvatarData = {
    body: BodyUpdateMyAvatar;
    path?: never;
    query?: never;
    url: '/api/v1/auth/me/avatar';
};

export type PutApiV1AuthMeAvatarErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PutApiV1AuthMeAvatarError = PutApiV1AuthMeAvatarErrors[keyof PutApiV1AuthMeAvatarErrors];

export type PutApiV1AuthMeAvatarResponses = {
    /**
     * Successful Response
     */
    200: UserOut;
};

export type PutApiV1AuthMeAvatarResponse = PutApiV1AuthMeAvatarResponses[keyof PutApiV1AuthMeAvatarResponses];

export type PostApiV1CatalogUploadsData = {
    body: BodyUploadTrack;
    path?: never;
    query?: never;
    url: '/api/v1/catalog/uploads';
};

export type PostApiV1CatalogUploadsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostApiV1CatalogUploadsError = PostApiV1CatalogUploadsErrors[keyof PostApiV1CatalogUploadsErrors];

export type PostApiV1CatalogUploadsResponses = {
    /**
     * Successful Response
     */
    201: TrackOut;
};

export type PostApiV1CatalogUploadsResponse = PostApiV1CatalogUploadsResponses[keyof PostApiV1CatalogUploadsResponses];

export type PostApiV1CatalogUploadsZipData = {
    body: BodyUploadZip;
    path?: never;
    query?: never;
    url: '/api/v1/catalog/uploads/zip';
};

export type PostApiV1CatalogUploadsZipErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostApiV1CatalogUploadsZipError = PostApiV1CatalogUploadsZipErrors[keyof PostApiV1CatalogUploadsZipErrors];

export type PostApiV1CatalogUploadsZipResponses = {
    /**
     * Successful Response
     */
    201: ImportJobOut;
};

export type PostApiV1CatalogUploadsZipResponse = PostApiV1CatalogUploadsZipResponses[keyof PostApiV1CatalogUploadsZipResponses];

export type GetApiV1CatalogImportsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/catalog/imports';
};

export type GetApiV1CatalogImportsResponses = {
    /**
     * Response Listimports
     *
     * Successful Response
     */
    200: Array<ImportJobOut>;
};

export type GetApiV1CatalogImportsResponse = GetApiV1CatalogImportsResponses[keyof GetApiV1CatalogImportsResponses];

export type GetApiV1CatalogJobsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/catalog/jobs';
};

export type GetApiV1CatalogJobsResponses = {
    /**
     * Response Listjobs
     *
     * Successful Response
     */
    200: Array<JobOut>;
};

export type GetApiV1CatalogJobsResponse = GetApiV1CatalogJobsResponses[keyof GetApiV1CatalogJobsResponses];

export type PostApiV1CatalogJobsByJobIdCancelData = {
    body?: never;
    path: {
        /**
         * Job Id
         */
        job_id: string;
    };
    query?: never;
    url: '/api/v1/catalog/jobs/{job_id}/cancel';
};

export type PostApiV1CatalogJobsByJobIdCancelErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostApiV1CatalogJobsByJobIdCancelError = PostApiV1CatalogJobsByJobIdCancelErrors[keyof PostApiV1CatalogJobsByJobIdCancelErrors];

export type PostApiV1CatalogJobsByJobIdCancelResponses = {
    /**
     * Successful Response
     */
    200: JobOut;
};

export type PostApiV1CatalogJobsByJobIdCancelResponse = PostApiV1CatalogJobsByJobIdCancelResponses[keyof PostApiV1CatalogJobsByJobIdCancelResponses];

export type PostApiV1CatalogJobsByJobIdRetryFailedData = {
    body?: never;
    path: {
        /**
         * Job Id
         */
        job_id: string;
    };
    query?: never;
    url: '/api/v1/catalog/jobs/{job_id}/retry-failed';
};

export type PostApiV1CatalogJobsByJobIdRetryFailedErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostApiV1CatalogJobsByJobIdRetryFailedError = PostApiV1CatalogJobsByJobIdRetryFailedErrors[keyof PostApiV1CatalogJobsByJobIdRetryFailedErrors];

export type PostApiV1CatalogJobsByJobIdRetryFailedResponses = {
    /**
     * Successful Response
     */
    200: JobOut;
};

export type PostApiV1CatalogJobsByJobIdRetryFailedResponse = PostApiV1CatalogJobsByJobIdRetryFailedResponses[keyof PostApiV1CatalogJobsByJobIdRetryFailedResponses];

export type GetApiV1CatalogImportsByImportIdData = {
    body?: never;
    path: {
        /**
         * Import Id
         */
        import_id: string;
    };
    query?: never;
    url: '/api/v1/catalog/imports/{import_id}';
};

export type GetApiV1CatalogImportsByImportIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetApiV1CatalogImportsByImportIdError = GetApiV1CatalogImportsByImportIdErrors[keyof GetApiV1CatalogImportsByImportIdErrors];

export type GetApiV1CatalogImportsByImportIdResponses = {
    /**
     * Successful Response
     */
    200: ImportJobOut;
};

export type GetApiV1CatalogImportsByImportIdResponse = GetApiV1CatalogImportsByImportIdResponses[keyof GetApiV1CatalogImportsByImportIdResponses];

export type GetApiV1CatalogTracksData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Q
         */
        q?: string | null;
        /**
         * Artist
         */
        artist?: string | null;
        /**
         * Artist Id
         */
        artist_id?: string | null;
        /**
         * Status
         */
        status?: TrackStatus | null;
        /**
         * Sort
         */
        sort?: 'imported_at' | 'duration' | 'title' | 'artist';
        /**
         * Order
         */
        order?: 'asc' | 'desc';
        /**
         * Limit
         */
        limit?: number;
        /**
         * Offset
         */
        offset?: number;
    };
    url: '/api/v1/catalog/tracks';
};

export type GetApiV1CatalogTracksErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetApiV1CatalogTracksError = GetApiV1CatalogTracksErrors[keyof GetApiV1CatalogTracksErrors];

export type GetApiV1CatalogTracksResponses = {
    /**
     * Successful Response
     */
    200: TrackListOut;
};

export type GetApiV1CatalogTracksResponse = GetApiV1CatalogTracksResponses[keyof GetApiV1CatalogTracksResponses];

export type PostApiV1CatalogTracksBulkDeleteData = {
    body: DeleteTracksBody;
    path?: never;
    query?: never;
    url: '/api/v1/catalog/tracks/bulk-delete';
};

export type PostApiV1CatalogTracksBulkDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostApiV1CatalogTracksBulkDeleteError = PostApiV1CatalogTracksBulkDeleteErrors[keyof PostApiV1CatalogTracksBulkDeleteErrors];

export type PostApiV1CatalogTracksBulkDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type PostApiV1CatalogTracksBulkDeleteResponse = PostApiV1CatalogTracksBulkDeleteResponses[keyof PostApiV1CatalogTracksBulkDeleteResponses];

export type DeleteApiV1CatalogTracksByTrackIdData = {
    body?: never;
    path: {
        /**
         * Track Id
         */
        track_id: string;
    };
    query?: never;
    url: '/api/v1/catalog/tracks/{track_id}';
};

export type DeleteApiV1CatalogTracksByTrackIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteApiV1CatalogTracksByTrackIdError = DeleteApiV1CatalogTracksByTrackIdErrors[keyof DeleteApiV1CatalogTracksByTrackIdErrors];

export type DeleteApiV1CatalogTracksByTrackIdResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteApiV1CatalogTracksByTrackIdResponse = DeleteApiV1CatalogTracksByTrackIdResponses[keyof DeleteApiV1CatalogTracksByTrackIdResponses];

export type GetApiV1CatalogTracksByTrackIdData = {
    body?: never;
    path: {
        /**
         * Track Id
         */
        track_id: string;
    };
    query?: never;
    url: '/api/v1/catalog/tracks/{track_id}';
};

export type GetApiV1CatalogTracksByTrackIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetApiV1CatalogTracksByTrackIdError = GetApiV1CatalogTracksByTrackIdErrors[keyof GetApiV1CatalogTracksByTrackIdErrors];

export type GetApiV1CatalogTracksByTrackIdResponses = {
    /**
     * Successful Response
     */
    200: TrackOut;
};

export type GetApiV1CatalogTracksByTrackIdResponse = GetApiV1CatalogTracksByTrackIdResponses[keyof GetApiV1CatalogTracksByTrackIdResponses];

export type PatchApiV1CatalogTracksByTrackIdData = {
    body: UpdateTrackBody;
    path: {
        /**
         * Track Id
         */
        track_id: string;
    };
    query?: never;
    url: '/api/v1/catalog/tracks/{track_id}';
};

export type PatchApiV1CatalogTracksByTrackIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PatchApiV1CatalogTracksByTrackIdError = PatchApiV1CatalogTracksByTrackIdErrors[keyof PatchApiV1CatalogTracksByTrackIdErrors];

export type PatchApiV1CatalogTracksByTrackIdResponses = {
    /**
     * Successful Response
     */
    200: TrackOut;
};

export type PatchApiV1CatalogTracksByTrackIdResponse = PatchApiV1CatalogTracksByTrackIdResponses[keyof PatchApiV1CatalogTracksByTrackIdResponses];

export type GetApiV1CatalogTracksByTrackIdCoverData = {
    body?: never;
    path: {
        /**
         * Track Id
         */
        track_id: string;
    };
    query?: never;
    url: '/api/v1/catalog/tracks/{track_id}/cover';
};

export type GetApiV1CatalogTracksByTrackIdCoverErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetApiV1CatalogTracksByTrackIdCoverError = GetApiV1CatalogTracksByTrackIdCoverErrors[keyof GetApiV1CatalogTracksByTrackIdCoverErrors];

export type GetApiV1CatalogTracksByTrackIdCoverResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type PutApiV1CatalogTracksByTrackIdCoverData = {
    body: BodyUpdateTrackCover;
    path: {
        /**
         * Track Id
         */
        track_id: string;
    };
    query?: never;
    url: '/api/v1/catalog/tracks/{track_id}/cover';
};

export type PutApiV1CatalogTracksByTrackIdCoverErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PutApiV1CatalogTracksByTrackIdCoverError = PutApiV1CatalogTracksByTrackIdCoverErrors[keyof PutApiV1CatalogTracksByTrackIdCoverErrors];

export type PutApiV1CatalogTracksByTrackIdCoverResponses = {
    /**
     * Successful Response
     */
    200: TrackOut;
};

export type PutApiV1CatalogTracksByTrackIdCoverResponse = PutApiV1CatalogTracksByTrackIdCoverResponses[keyof PutApiV1CatalogTracksByTrackIdCoverResponses];

export type GetApiV1CatalogTracksByTrackIdAudioData = {
    body?: never;
    headers?: {
        /**
         * Range
         */
        Range?: string | null;
    };
    path: {
        /**
         * Track Id
         */
        track_id: string;
    };
    query?: never;
    url: '/api/v1/catalog/tracks/{track_id}/audio';
};

export type GetApiV1CatalogTracksByTrackIdAudioErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetApiV1CatalogTracksByTrackIdAudioError = GetApiV1CatalogTracksByTrackIdAudioErrors[keyof GetApiV1CatalogTracksByTrackIdAudioErrors];

export type GetApiV1CatalogTracksByTrackIdAudioResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetApiV1CatalogTracksByTrackIdWaveformData = {
    body?: never;
    path: {
        /**
         * Track Id
         */
        track_id: string;
    };
    query?: never;
    url: '/api/v1/catalog/tracks/{track_id}/waveform';
};

export type GetApiV1CatalogTracksByTrackIdWaveformErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetApiV1CatalogTracksByTrackIdWaveformError = GetApiV1CatalogTracksByTrackIdWaveformErrors[keyof GetApiV1CatalogTracksByTrackIdWaveformErrors];

export type GetApiV1CatalogTracksByTrackIdWaveformResponses = {
    /**
     * Successful Response
     */
    200: WaveformOut;
};

export type GetApiV1CatalogTracksByTrackIdWaveformResponse = GetApiV1CatalogTracksByTrackIdWaveformResponses[keyof GetApiV1CatalogTracksByTrackIdWaveformResponses];

export type GetApiV1CatalogArtistsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Q
         */
        q?: string | null;
        /**
         * Sort
         */
        sort?: 'name' | 'track_count' | 'created_at';
        /**
         * Order
         */
        order?: 'asc' | 'desc';
        /**
         * Limit
         */
        limit?: number;
        /**
         * Offset
         */
        offset?: number;
    };
    url: '/api/v1/catalog/artists';
};

export type GetApiV1CatalogArtistsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetApiV1CatalogArtistsError = GetApiV1CatalogArtistsErrors[keyof GetApiV1CatalogArtistsErrors];

export type GetApiV1CatalogArtistsResponses = {
    /**
     * Successful Response
     */
    200: ArtistListOut;
};

export type GetApiV1CatalogArtistsResponse = GetApiV1CatalogArtistsResponses[keyof GetApiV1CatalogArtistsResponses];

export type PostApiV1CatalogArtistsData = {
    body: CreateArtistBody;
    path?: never;
    query?: never;
    url: '/api/v1/catalog/artists';
};

export type PostApiV1CatalogArtistsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostApiV1CatalogArtistsError = PostApiV1CatalogArtistsErrors[keyof PostApiV1CatalogArtistsErrors];

export type PostApiV1CatalogArtistsResponses = {
    /**
     * Successful Response
     */
    201: ArtistOut;
};

export type PostApiV1CatalogArtistsResponse = PostApiV1CatalogArtistsResponses[keyof PostApiV1CatalogArtistsResponses];

export type DeleteApiV1CatalogArtistsByArtistIdData = {
    body?: never;
    path: {
        /**
         * Artist Id
         */
        artist_id: string;
    };
    query?: never;
    url: '/api/v1/catalog/artists/{artist_id}';
};

export type DeleteApiV1CatalogArtistsByArtistIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteApiV1CatalogArtistsByArtistIdError = DeleteApiV1CatalogArtistsByArtistIdErrors[keyof DeleteApiV1CatalogArtistsByArtistIdErrors];

export type DeleteApiV1CatalogArtistsByArtistIdResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteApiV1CatalogArtistsByArtistIdResponse = DeleteApiV1CatalogArtistsByArtistIdResponses[keyof DeleteApiV1CatalogArtistsByArtistIdResponses];

export type GetApiV1CatalogArtistsByArtistIdData = {
    body?: never;
    path: {
        /**
         * Artist Id
         */
        artist_id: string;
    };
    query?: never;
    url: '/api/v1/catalog/artists/{artist_id}';
};

export type GetApiV1CatalogArtistsByArtistIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetApiV1CatalogArtistsByArtistIdError = GetApiV1CatalogArtistsByArtistIdErrors[keyof GetApiV1CatalogArtistsByArtistIdErrors];

export type GetApiV1CatalogArtistsByArtistIdResponses = {
    /**
     * Successful Response
     */
    200: ArtistOut;
};

export type GetApiV1CatalogArtistsByArtistIdResponse = GetApiV1CatalogArtistsByArtistIdResponses[keyof GetApiV1CatalogArtistsByArtistIdResponses];

export type GetApiV1CatalogArtistsByArtistIdImageData = {
    body?: never;
    path: {
        /**
         * Artist Id
         */
        artist_id: string;
    };
    query?: never;
    url: '/api/v1/catalog/artists/{artist_id}/image';
};

export type GetApiV1CatalogArtistsByArtistIdImageErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetApiV1CatalogArtistsByArtistIdImageError = GetApiV1CatalogArtistsByArtistIdImageErrors[keyof GetApiV1CatalogArtistsByArtistIdImageErrors];

export type GetApiV1CatalogArtistsByArtistIdImageResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type PostApiV1SearchTextData = {
    body: SearchTextBody;
    path?: never;
    query?: never;
    url: '/api/v1/search/text';
};

export type PostApiV1SearchTextErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostApiV1SearchTextError = PostApiV1SearchTextErrors[keyof PostApiV1SearchTextErrors];

export type PostApiV1SearchTextResponses = {
    /**
     * Successful Response
     */
    200: SearchResponseOut;
};

export type PostApiV1SearchTextResponse = PostApiV1SearchTextResponses[keyof PostApiV1SearchTextResponses];

export type PostApiV1SearchAudioData = {
    body: BodySearchAudio;
    path?: never;
    query?: {
        /**
         * Top K
         */
        top_k?: number;
    };
    url: '/api/v1/search/audio';
};

export type PostApiV1SearchAudioErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostApiV1SearchAudioError = PostApiV1SearchAudioErrors[keyof PostApiV1SearchAudioErrors];

export type PostApiV1SearchAudioResponses = {
    /**
     * Successful Response
     */
    200: SearchResponseOut;
};

export type PostApiV1SearchAudioResponse = PostApiV1SearchAudioResponses[keyof PostApiV1SearchAudioResponses];

export type GetApiV1SearchSimilarByTrackIdData = {
    body?: never;
    path: {
        /**
         * Track Id
         */
        track_id: string;
    };
    query?: {
        /**
         * Top K
         */
        top_k?: number;
    };
    url: '/api/v1/search/similar/{track_id}';
};

export type GetApiV1SearchSimilarByTrackIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetApiV1SearchSimilarByTrackIdError = GetApiV1SearchSimilarByTrackIdErrors[keyof GetApiV1SearchSimilarByTrackIdErrors];

export type GetApiV1SearchSimilarByTrackIdResponses = {
    /**
     * Successful Response
     */
    200: SearchResponseOut;
};

export type GetApiV1SearchSimilarByTrackIdResponse = GetApiV1SearchSimilarByTrackIdResponses[keyof GetApiV1SearchSimilarByTrackIdResponses];

export type GetApiV1GraphData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Focus Track Id
         */
        focus_track_id?: string | null;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/graph';
};

export type GetApiV1GraphErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetApiV1GraphError = GetApiV1GraphErrors[keyof GetApiV1GraphErrors];

export type GetApiV1GraphResponses = {
    /**
     * Successful Response
     */
    200: GraphResponseOut;
};

export type GetApiV1GraphResponse = GetApiV1GraphResponses[keyof GetApiV1GraphResponses];

export type GetApiV1ChatsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/chats';
};

export type GetApiV1ChatsResponses = {
    /**
     * Response Listchats
     *
     * Successful Response
     */
    200: Array<ChatSummaryOut>;
};

export type GetApiV1ChatsResponse = GetApiV1ChatsResponses[keyof GetApiV1ChatsResponses];

export type PostApiV1ChatsData = {
    body: CreateChatBody;
    path?: never;
    query?: never;
    url: '/api/v1/chats';
};

export type PostApiV1ChatsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostApiV1ChatsError = PostApiV1ChatsErrors[keyof PostApiV1ChatsErrors];

export type PostApiV1ChatsResponses = {
    /**
     * Successful Response
     */
    200: ChatDetailOut;
};

export type PostApiV1ChatsResponse = PostApiV1ChatsResponses[keyof PostApiV1ChatsResponses];

export type GetApiV1ChatsByChatIdData = {
    body?: never;
    path: {
        /**
         * Chat Id
         */
        chat_id: string;
    };
    query?: never;
    url: '/api/v1/chats/{chat_id}';
};

export type GetApiV1ChatsByChatIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetApiV1ChatsByChatIdError = GetApiV1ChatsByChatIdErrors[keyof GetApiV1ChatsByChatIdErrors];

export type GetApiV1ChatsByChatIdResponses = {
    /**
     * Successful Response
     */
    200: ChatDetailOut;
};

export type GetApiV1ChatsByChatIdResponse = GetApiV1ChatsByChatIdResponses[keyof GetApiV1ChatsByChatIdResponses];

export type PostApiV1ChatsByChatIdMessagesData = {
    body: AppendMessageBody;
    path: {
        /**
         * Chat Id
         */
        chat_id: string;
    };
    query?: never;
    url: '/api/v1/chats/{chat_id}/messages';
};

export type PostApiV1ChatsByChatIdMessagesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostApiV1ChatsByChatIdMessagesError = PostApiV1ChatsByChatIdMessagesErrors[keyof PostApiV1ChatsByChatIdMessagesErrors];

export type PostApiV1ChatsByChatIdMessagesResponses = {
    /**
     * Successful Response
     */
    200: AppendMessageOut;
};

export type PostApiV1ChatsByChatIdMessagesResponse = PostApiV1ChatsByChatIdMessagesResponses[keyof PostApiV1ChatsByChatIdMessagesResponses];

export type PostApiV1ChatsByChatIdReplyStreamData = {
    body?: never;
    path: {
        /**
         * Chat Id
         */
        chat_id: string;
    };
    query?: never;
    url: '/api/v1/chats/{chat_id}/reply/stream';
};

export type PostApiV1ChatsByChatIdReplyStreamErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostApiV1ChatsByChatIdReplyStreamError = PostApiV1ChatsByChatIdReplyStreamErrors[keyof PostApiV1ChatsByChatIdReplyStreamErrors];

export type PostApiV1ChatsByChatIdReplyStreamResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type PostApiV1ChatsByChatIdMessagesStreamData = {
    body: AppendMessageBody;
    path: {
        /**
         * Chat Id
         */
        chat_id: string;
    };
    query?: never;
    url: '/api/v1/chats/{chat_id}/messages/stream';
};

export type PostApiV1ChatsByChatIdMessagesStreamErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostApiV1ChatsByChatIdMessagesStreamError = PostApiV1ChatsByChatIdMessagesStreamErrors[keyof PostApiV1ChatsByChatIdMessagesStreamErrors];

export type PostApiV1ChatsByChatIdMessagesStreamResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetApiV1PlaylistsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/playlists';
};

export type GetApiV1PlaylistsResponses = {
    /**
     * Response Listplaylists
     *
     * Successful Response
     */
    200: Array<PlaylistSummaryOut>;
};

export type GetApiV1PlaylistsResponse = GetApiV1PlaylistsResponses[keyof GetApiV1PlaylistsResponses];

export type PostApiV1PlaylistsData = {
    body: CreatePlaylistBody;
    path?: never;
    query?: never;
    url: '/api/v1/playlists';
};

export type PostApiV1PlaylistsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostApiV1PlaylistsError = PostApiV1PlaylistsErrors[keyof PostApiV1PlaylistsErrors];

export type PostApiV1PlaylistsResponses = {
    /**
     * Successful Response
     */
    200: PlaylistDetailOut;
};

export type PostApiV1PlaylistsResponse = PostApiV1PlaylistsResponses[keyof PostApiV1PlaylistsResponses];

export type DeleteApiV1PlaylistsByPlaylistIdData = {
    body?: never;
    path: {
        /**
         * Playlist Id
         */
        playlist_id: string;
    };
    query?: never;
    url: '/api/v1/playlists/{playlist_id}';
};

export type DeleteApiV1PlaylistsByPlaylistIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteApiV1PlaylistsByPlaylistIdError = DeleteApiV1PlaylistsByPlaylistIdErrors[keyof DeleteApiV1PlaylistsByPlaylistIdErrors];

export type DeleteApiV1PlaylistsByPlaylistIdResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteApiV1PlaylistsByPlaylistIdResponse = DeleteApiV1PlaylistsByPlaylistIdResponses[keyof DeleteApiV1PlaylistsByPlaylistIdResponses];

export type GetApiV1PlaylistsByPlaylistIdData = {
    body?: never;
    path: {
        /**
         * Playlist Id
         */
        playlist_id: string;
    };
    query?: never;
    url: '/api/v1/playlists/{playlist_id}';
};

export type GetApiV1PlaylistsByPlaylistIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetApiV1PlaylistsByPlaylistIdError = GetApiV1PlaylistsByPlaylistIdErrors[keyof GetApiV1PlaylistsByPlaylistIdErrors];

export type GetApiV1PlaylistsByPlaylistIdResponses = {
    /**
     * Successful Response
     */
    200: PlaylistDetailOut;
};

export type GetApiV1PlaylistsByPlaylistIdResponse = GetApiV1PlaylistsByPlaylistIdResponses[keyof GetApiV1PlaylistsByPlaylistIdResponses];

export type PatchApiV1PlaylistsByPlaylistIdData = {
    body: UpdatePlaylistBody;
    path: {
        /**
         * Playlist Id
         */
        playlist_id: string;
    };
    query?: never;
    url: '/api/v1/playlists/{playlist_id}';
};

export type PatchApiV1PlaylistsByPlaylistIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PatchApiV1PlaylistsByPlaylistIdError = PatchApiV1PlaylistsByPlaylistIdErrors[keyof PatchApiV1PlaylistsByPlaylistIdErrors];

export type PatchApiV1PlaylistsByPlaylistIdResponses = {
    /**
     * Successful Response
     */
    200: PlaylistDetailOut;
};

export type PatchApiV1PlaylistsByPlaylistIdResponse = PatchApiV1PlaylistsByPlaylistIdResponses[keyof PatchApiV1PlaylistsByPlaylistIdResponses];

export type DeleteApiV1PlaylistsByPlaylistIdTracksData = {
    body: RemovePlaylistTracksBody;
    path: {
        /**
         * Playlist Id
         */
        playlist_id: string;
    };
    query?: never;
    url: '/api/v1/playlists/{playlist_id}/tracks';
};

export type DeleteApiV1PlaylistsByPlaylistIdTracksErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteApiV1PlaylistsByPlaylistIdTracksError = DeleteApiV1PlaylistsByPlaylistIdTracksErrors[keyof DeleteApiV1PlaylistsByPlaylistIdTracksErrors];

export type DeleteApiV1PlaylistsByPlaylistIdTracksResponses = {
    /**
     * Successful Response
     */
    200: PlaylistDetailOut;
};

export type DeleteApiV1PlaylistsByPlaylistIdTracksResponse = DeleteApiV1PlaylistsByPlaylistIdTracksResponses[keyof DeleteApiV1PlaylistsByPlaylistIdTracksResponses];

export type PostApiV1PlaylistsByPlaylistIdTracksData = {
    body: PlaylistTracksBody;
    path: {
        /**
         * Playlist Id
         */
        playlist_id: string;
    };
    query?: never;
    url: '/api/v1/playlists/{playlist_id}/tracks';
};

export type PostApiV1PlaylistsByPlaylistIdTracksErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostApiV1PlaylistsByPlaylistIdTracksError = PostApiV1PlaylistsByPlaylistIdTracksErrors[keyof PostApiV1PlaylistsByPlaylistIdTracksErrors];

export type PostApiV1PlaylistsByPlaylistIdTracksResponses = {
    /**
     * Successful Response
     */
    200: PlaylistDetailOut;
};

export type PostApiV1PlaylistsByPlaylistIdTracksResponse = PostApiV1PlaylistsByPlaylistIdTracksResponses[keyof PostApiV1PlaylistsByPlaylistIdTracksResponses];

export type PutApiV1PlaylistsByPlaylistIdTracksOrderData = {
    body: ReorderPlaylistBody;
    path: {
        /**
         * Playlist Id
         */
        playlist_id: string;
    };
    query?: never;
    url: '/api/v1/playlists/{playlist_id}/tracks/order';
};

export type PutApiV1PlaylistsByPlaylistIdTracksOrderErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PutApiV1PlaylistsByPlaylistIdTracksOrderError = PutApiV1PlaylistsByPlaylistIdTracksOrderErrors[keyof PutApiV1PlaylistsByPlaylistIdTracksOrderErrors];

export type PutApiV1PlaylistsByPlaylistIdTracksOrderResponses = {
    /**
     * Successful Response
     */
    200: PlaylistDetailOut;
};

export type PutApiV1PlaylistsByPlaylistIdTracksOrderResponse = PutApiV1PlaylistsByPlaylistIdTracksOrderResponses[keyof PutApiV1PlaylistsByPlaylistIdTracksOrderResponses];

export type GetApiV1HealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/health';
};

export type GetApiV1HealthResponses = {
    /**
     * Response Health
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type GetApiV1HealthResponse = GetApiV1HealthResponses[keyof GetApiV1HealthResponses];
